* 句子结构
1. 主谓
2. 主谓宾
3. 主系表
   1. 系动词
      1. be动词
      2. 感官动词 look taste
      3. 表变化的动词，grow drop turn
      4. 表保持的动词，remain
      5. 表表象：seem
      6. 表结果：approve
4. 主谓双宾
5. 主谓宾+宾补
* 谓语
1. 什么可以做谓语？：有时态和语态的实意动词或系动词
2. 谓语只能是动词，动词只能做谓语
3. 分析长难句的时候先找动词，即先找谓语
4. 动词的不做谓语时的词性，即非谓语动词
   1. v+ing 表主动或进行，动名词/现在分词
   2. v+ed  表被动或完成  过去分词
   3. to do 表目的        不定式
** 动词的分类
1. 实意动词：有实在意义的动词
2. 连系动词：be动词
3. 情态动词：带有主观情绪
   1. must/could/should/could/ have done : 表示对过去完成某事的设想
4. 助动词：帮助谓语构成否定、疑问、时态、语态。
* 主语
** 什么可以做主语？
1. 代词
2. 名词
3. 非-谓语动词
4. 从句
** 注意使用不同句式来强调主体和逻辑
1. there be
2. 形式代词代指主语
3. 被动
** 从句
引导词 + 句子
*** 引导词
- that
- whether
- why、what、which、whom、how 等特殊疑问词
* present simple
** 使用助动词do dose 构成否定或疑问
#+begin_src sh
  // 他来自哪里
  Where does(这里跟主语（单/复）一致) he come(这里不再需要保持一致，助动做过了) from?

  // 你妹妹玩网球么
  Does your sister play tennis?
#+end_src
* present simple .vs. present continous
** be always doing VS always do
#+begin_src sh
  // 我总是开车去上班（我每次都是开车去上班）
  I always go to work by car.

  // 我总丢东西(very often)
  I am always losing things.

  // 你天天玩你那破电脑
  You are always playing computer.

  // 他总是在抱怨
  He is always complaining = He complains too much
#+end_src
** 错题
- 这有人坐了么
  Is anybody sitting here?

- 我好饿
  I am feeling hungry

- 他生病了么？
  Is he ill？  
* 特殊形式的分词
|--------+---------+-----------+----------|
| 原型   | 过去式  | 过去分词  | 现在分词 |
| sleep  | slept   |           |          |
| teach  | taught  |           |          |
| sell   | sold    |           |          |
| fell   | fell    |           |          |
| hurt   | hurt    |           |          |
| throw  | threw   |           |          |
| fly    | flew    |           |          |
| hear   | heard   |           |          |
| want   | wanted  |           |          |
| rid    | ridden  |           |          |
| write  | wrote   | written   | writing  |
| wait   |         |           | waiting  |
| read   | read    |           |          |
| ill    | ill     |           |          |
| eat    | ate     | eaten     |          |
| forget |         | forgotten |          |
| apply  | applied |           |          |
| fall   | fell    |           |          |
| come   | came    | come      |          |
| break  | broke   | broken    |          |
* past simple VS past continous
** 错题
- 我昨天散步时突然听到脚步声，有人在跟踪我，我很害怕，然后开始跑
  I was walking along the street when suddenly I heard footsteps behind me. Sombody was following me. I was scared and I started to run
* present perfect VS present perfect continous
1. 通常是recently的动作
2. 通常对now产生了result
** difference between gone(to) and been(to)
1. He has gone to China. // 已经出发去中国了，now在路上或者在中国
2. He has been to China. // 已经去过了，now回来了
** 使用haven't done somthing since/for来表示多久没做过没事
- 上次见Tom还是星期一
  I haven't seen Tom since Monday.
  I haven't seen Tom for few days.
** 错题
- 你见过最美的地方是？
  What's the most beautiful place you have ever visited?//注意语序：是you have不是have you

- 这是这段时间以来最好的假日
  It's the best holiday I have had for a long time  // 注意不是否定：I have had 不是 I haven't had


- 你等很长时间了么
  Have you been waiting long // 不是waiting for long


- 她去年就结婚了
  She has been married since last years // 这句没懂 不是marring


- 你们结婚多久了？
  How long have you been married？// 不是marring


- 你们什么时候结婚的
  When did you get married // 不是 When did you marry


- 我戒掉cafe了，上次喝已经是一年以前了
  I gave up drinking cafe. I haven't drank it for a year.


- 我不太认识Tom，我们只见过几次
  I don't know Tom well. We've only met a few times.
* present perfect VS past simple
** 错题
- 你在哪出生
  Where were you born？ // 不是 Where did you born.难道是did you been born = were you born?


- 爱因斯坦是提出相对论的科学家
Albert Einstein was the scientist who developed the theory of relativity.

- It was = It has been
  // 它原来放在那。
  It was been there. // 不是It has been there


- Mr Lee worked in a bank for 15 years. // 不是has been working


- My grandfather died before I was born. // 不是was died
  I never met him // 不是 I've never met him


- 你以前住在北京，现在住在苏州
  How long have you been lived in Suzhou?
  How long did you live in Beijing? // 北京是过去的。1. 不是have you been lived。 2. 不是did you lived 助动词已经反应了时态了
* past perfect
past perfect ：一般由一个past simple 当做故事的一个起点，在这个起点之前完成的，对起点时刻有result的时候用pastperfect
** 错题
- I offered sue something to eat， but she wasn't hungry.
  She had just had breakfast // 不是She just had breakfast，这里没有表示出已经吃完了
* past perfect continuous
** 错题
- 我昨天去我朋友家时，他们嘴里有食物
  They were eating // 不是they had been eating，不是他们刚刚在吃


- 我昨天去我朋友家时，他们嘴里没有食物，但是胃里全是食物
  They had been eating // 吃是持续动作，类似rain
* have VS have got
** 错题
- 我牙疼
  'Are you feeling OK?' 'NO, +I'm having+ a toothache'
  // I've got a toothache
  // I have a toothache


- 他几周前（不是最近了，不用present perfect）有了第二个孩子
  He had a baby a few weeks ago. It's his second child.//这里是几周前，不是强调刚刚生完，不用完成时
* used to VS do
使用助动词表否定
- 她曾经不喜欢读报纸（现在喜欢）
  She +used not to+ read newspapers.
  She didn't used to read newspapers. 


- 他曾经不喜欢喝茶（现在喜欢）
  She used not to drink tea.
  She didn't used to drink tea.
